#!/usr/bin/env bash
#
# build-android
#
# This source file is part of the Swift.org open source project
#
# Copyright (c) 2014 - 2017 Apple Inc. and the Swift project authors
# Licensed under Apache License v2.0 with Runtime Library Exception
#
# See https://swift.org/LICENSE.txt for license information
# See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors

set -e

cd "$(dirname $0)/.." || exit 1
SWIFT_PATH=$PWD

ANDROID_NDK_PATH="${ANDROID_NDK_PATH:?Please set the Android NDK path in the ANDROID_NDK_PATH environment variable}"
SWIFT_ANDROID_BUILD_PATH="${SWIFT_PATH}/build/Ninja-ReleaseAssert"
SWIFT_ANDROID_TOOLCHAIN_PATH="${SWIFT_PATH}/swift-android-toolchain"

cd ${SWIFT_PATH}/swift-corelibs-libdispatch 
sh autogen.sh
env \
    CC="$SWIFT_ANDROID_BUILD_PATH/llvm-linux-x86_64/bin/clang" \
    CXX="$SWIFT_ANDROID_BUILD_PATH/llvm-linux-x86_64/bin/clang++" \
    SWIFTC="$SWIFT_ANDROID_BUILD_PATH/swift-linux-x86_64/bin/swiftc" \
    CFLAGS="-I$ANDROID_NDK_PATH/sysroot/usr/include" \
    CPPFLAGS="-I$ANDROID_NDK_PATH/sysroot/usr/include -DTARGET_OS_EMBEDDED" \
    ./configure \
        --with-swift-toolchain="$SWIFT_ANDROID_TOOLCHAIN_PATH/usr" \
        --with-build-variant=release \
        --enable-android \
        --host=arm-linux-androideabi \
        --with-android-ndk=$ANDROID_NDK_PATH \
        --with-android-api-level=21 \
        --disable-build-tests \
        --prefix=$SWIFT_ANDROID_TOOLCHAIN_PATH/usr

make

cp ${SWIFT_PATH}/swift-corelibs-libdispatch/src/.libs/libdispatch.so $SWIFT_ANDROID_TOOLCHAIN_PATH/usr/lib/swift/android/armv7
cp ${SWIFT_PATH}/swift-corelibs-libdispatch/src/swift/Dispatch.{swiftmodule,swiftdoc} $SWIFT_ANDROID_TOOLCHAIN_PATH/usr/lib/swift/android/armv7

